### ISSUE TITLE
Can't use redis-graph example

### ISSUE THREAD

**Issue by luisantonioig** [RedisLabs/redisgraph-go#1]
I am trying to use redis-graph with the README's example but all I get is the next error:

    $ go run main.go 
    # command-line-arguments
    ./main.go:5:2: imported and not used: "github.com/redislabs/redisgraph-go" as redisgraph
    ./main.go:12:11: undefined: Graph
    ./main.go:14:13: undefined: Node
    ./main.go:25:30: undefined: Node
    ./main.go:33:39: undefined: Edge

**Comment by itamarhaber** [comment]
@luisantonioig - thanks, fixed the example - please try now.
